# Generated by Django 4.0.1 on 2022-05-30 21:07

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('number_of_rooms', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('size_sq_m', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('story', models.CharField(default='0', max_length=7, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('room_details', models.TextField(blank=True, max_length=1024, null=True)),
                ('flooring', models.CharField(blank=True, max_length=128, null=True)),
                ('furnishing', models.TextField(blank=True, max_length=512, null=True)),
                ('kitchen_info', models.TextField(blank=True, max_length=512, null=True)),
                ('technical_equipment', models.TextField(blank=True, help_text='Washing machine, dryer, TV, etc.', max_length=512, null=True)),
                ('has_internet', models.BooleanField(default=True)),
                ('internet_info', models.CharField(blank=True, max_length=256, null=True)),
                ('specials', models.TextField(blank=True, help_text='Extra features that make this apartment attractive', max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surroundings', models.TextField(blank=True, max_length=1024, null=True)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='broker.address')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('real_estate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='listings.realestate')),
                ('number_of_stories', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('date_of_construction', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('rental', 'RENTAL'), ('for_sale', 'FOR_SALE')], default='rental', max_length=8)),
                ('currency', models.CharField(default='$', max_length=4)),
                ('rental_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('info_about_rental_price', models.CharField(blank=True, default='Does not include utilities', max_length=64, null=True)),
                ('for_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_down_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('short_description', models.CharField(default='A beautiful new vacancy', help_text='A short description of your listing', max_length=128)),
                ('long_description', models.TextField(blank=True, default='', help_text='A detailed description of your listing', max_length=1024, null=True)),
                ('date_available', models.DateField(default=datetime.date.today)),
                ('minimum_months', models.PositiveIntegerField(blank=True, default=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(128)])),
                ('maximum_months', models.PositiveIntegerField(blank=True, default=60, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(128)])),
                ('number_of_people', models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('limitations', models.CharField(blank=True, default='', help_text='Limiting factors to qualify for approval             (no smoking, must be full-time employee, etc.)', max_length=256, null=True)),
                ('pets_ok', models.BooleanField(default=False)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.apartment')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='broker.contact')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.house')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='assets/house.jpg', upload_to='uploads/listings/')),
                ('image_name', models.CharField(default='untitled', max_length=32)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.apartment')),
                ('listing', models.ManyToManyField(to='listings.Listing')),
                ('real_estate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.realestate')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.house')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.house'),
        ),
    ]
