# Generated by Django 4.0.1 on 2022-09-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_apartment_is_furnished'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='flooring_de',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='flooring_en',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='flooring_es',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='flooring_fr',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='flooring_it',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='furnishing_de',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='furnishing_en',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='furnishing_es',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='furnishing_fr',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='furnishing_it',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='internet_info_de',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='internet_info_en',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='internet_info_es',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='internet_info_fr',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='internet_info_it',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='kitchen_info_de',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='kitchen_info_en',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='kitchen_info_es',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='kitchen_info_fr',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='kitchen_info_it',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='room_details_de',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='room_details_en',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='room_details_es',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='room_details_fr',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='room_details_it',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='specials_de',
            field=models.TextField(blank=True, help_text='Extra features that make this apartment attractive', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='specials_en',
            field=models.TextField(blank=True, help_text='Extra features that make this apartment attractive', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='specials_es',
            field=models.TextField(blank=True, help_text='Extra features that make this apartment attractive', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='specials_fr',
            field=models.TextField(blank=True, help_text='Extra features that make this apartment attractive', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='specials_it',
            field=models.TextField(blank=True, help_text='Extra features that make this apartment attractive', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='technical_equipment_de',
            field=models.TextField(blank=True, help_text='Washing machine, dryer, TV, etc.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='technical_equipment_en',
            field=models.TextField(blank=True, help_text='Washing machine, dryer, TV, etc.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='technical_equipment_es',
            field=models.TextField(blank=True, help_text='Washing machine, dryer, TV, etc.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='technical_equipment_fr',
            field=models.TextField(blank=True, help_text='Washing machine, dryer, TV, etc.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='technical_equipment_it',
            field=models.TextField(blank=True, help_text='Washing machine, dryer, TV, etc.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_name_de',
            field=models.CharField(default='untitled', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_name_en',
            field=models.CharField(default='untitled', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_name_es',
            field=models.CharField(default='untitled', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_name_fr',
            field=models.CharField(default='untitled', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_name_it',
            field=models.CharField(default='untitled', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='info_about_rental_price_de',
            field=models.CharField(blank=True, default='Does not include utilities', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='info_about_rental_price_en',
            field=models.CharField(blank=True, default='Does not include utilities', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='info_about_rental_price_es',
            field=models.CharField(blank=True, default='Does not include utilities', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='info_about_rental_price_fr',
            field=models.CharField(blank=True, default='Does not include utilities', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='info_about_rental_price_it',
            field=models.CharField(blank=True, default='Does not include utilities', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='limitations_de',
            field=models.CharField(blank=True, default='', help_text='Limiting factors to qualify for approval             (no smoking, must be full-time employee, etc.)', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='limitations_en',
            field=models.CharField(blank=True, default='', help_text='Limiting factors to qualify for approval             (no smoking, must be full-time employee, etc.)', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='limitations_es',
            field=models.CharField(blank=True, default='', help_text='Limiting factors to qualify for approval             (no smoking, must be full-time employee, etc.)', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='limitations_fr',
            field=models.CharField(blank=True, default='', help_text='Limiting factors to qualify for approval             (no smoking, must be full-time employee, etc.)', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='limitations_it',
            field=models.CharField(blank=True, default='', help_text='Limiting factors to qualify for approval             (no smoking, must be full-time employee, etc.)', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_type_de',
            field=models.CharField(choices=[('rental', 'RENTAL'), ('for_sale', 'FOR_SALE')], default='rental', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_type_en',
            field=models.CharField(choices=[('rental', 'RENTAL'), ('for_sale', 'FOR_SALE')], default='rental', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_type_es',
            field=models.CharField(choices=[('rental', 'RENTAL'), ('for_sale', 'FOR_SALE')], default='rental', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_type_fr',
            field=models.CharField(choices=[('rental', 'RENTAL'), ('for_sale', 'FOR_SALE')], default='rental', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_type_it',
            field=models.CharField(choices=[('rental', 'RENTAL'), ('for_sale', 'FOR_SALE')], default='rental', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='long_description_de',
            field=models.TextField(blank=True, default='', help_text='A detailed description of your listing', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='long_description_en',
            field=models.TextField(blank=True, default='', help_text='A detailed description of your listing', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='long_description_es',
            field=models.TextField(blank=True, default='', help_text='A detailed description of your listing', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='long_description_fr',
            field=models.TextField(blank=True, default='', help_text='A detailed description of your listing', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='long_description_it',
            field=models.TextField(blank=True, default='', help_text='A detailed description of your listing', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='short_description_de',
            field=models.CharField(default='A beautiful new vacancy', help_text='A short description of your listing', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='short_description_en',
            field=models.CharField(default='A beautiful new vacancy', help_text='A short description of your listing', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='short_description_es',
            field=models.CharField(default='A beautiful new vacancy', help_text='A short description of your listing', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='short_description_fr',
            field=models.CharField(default='A beautiful new vacancy', help_text='A short description of your listing', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='short_description_it',
            field=models.CharField(default='A beautiful new vacancy', help_text='A short description of your listing', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='surroundings_de',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='surroundings_en',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='surroundings_es',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='surroundings_fr',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='surroundings_it',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
