# Generated by Django 4.0.1 on 2022-05-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='untitled', max_length=32, unique=True)),
                ('nav_name', models.CharField(default='Untitled', max_length=32)),
                ('content', models.TextField(default='Hello, World!', max_length=8192)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
