# Generated by Django 4.0.1 on 2022-09-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_de',
            field=models.TextField(default='Hello, World!', max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_en',
            field=models.TextField(default='Hello, World!', max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_es',
            field=models.TextField(default='Hello, World!', max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_fr',
            field=models.TextField(default='Hello, World!', max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='content_it',
            field=models.TextField(default='Hello, World!', max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name_de',
            field=models.CharField(default='untitled', max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name_en',
            field=models.CharField(default='untitled', max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name_es',
            field=models.CharField(default='untitled', max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name_fr',
            field=models.CharField(default='untitled', max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name_it',
            field=models.CharField(default='untitled', max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='page',
            name='nav_name_de',
            field=models.CharField(default='Untitled', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='nav_name_en',
            field=models.CharField(default='Untitled', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='nav_name_es',
            field=models.CharField(default='Untitled', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='nav_name_fr',
            field=models.CharField(default='Untitled', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='nav_name_it',
            field=models.CharField(default='Untitled', max_length=32, null=True),
        ),
    ]
