# Generated by Django 4.0 on 2022-09-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_name'),
        ('pages', '0002_page_content_de_page_content_en_page_content_es_and_more'),
    ]

    operations = [
    ]
