# Generated by Django 4.0 on 2022-09-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_merge_20220919_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name_de',
            field=models.CharField(default='untitled', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='name_en',
            field=models.CharField(default='untitled', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='name_es',
            field=models.CharField(default='untitled', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='name_fr',
            field=models.CharField(default='untitled', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='name_it',
            field=models.CharField(default='untitled', max_length=32, null=True),
        ),
    ]
