# Generated by Django 4.0.1 on 2022-05-30 21:07

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=32)),
                ('number', models.CharField(blank=True, max_length=8, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=16, null=True)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(blank=True, max_length=32, null=True)),
                ('country', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=32)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('possible', 'POSSIBLE'), ('pending', 'PENDING'), ('closed', 'CLOSED')], default='possible', max_length=8)),
                ('note', models.TextField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Seeking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeking_type', models.CharField(choices=[('rental', 'RENTAL'), ('for_sale', 'FOR_SALE')], default='rental', max_length=8)),
                ('max_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('max_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_number_of_rooms', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('min_size_qm', models.IntegerField(blank=True, default=20, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('number_of_persons', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('starting_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('number_of_months', models.IntegerField(blank=True, null=True)),
                ('must_be_furnished', models.BooleanField(default=False)),
                ('occupation', models.CharField(blank=True, help_text='Type of job that this tenant/buyer has', max_length=64, null=True)),
                ('is_smoker', models.BooleanField(default=False)),
                ('has_pets', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, max_length=2048, null=True)),
                ('contact_source', models.CharField(blank=True, help_text='How did this person find out about us?', max_length=64, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='broker.contact')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='broker.company')),
            ],
        ),
    ]
