# Generated by Django 4.0.1 on 2022-05-30 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broker', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
        migrations.AddField(
            model_name='matching',
            name='seeking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='broker.seeking'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.ManyToManyField(blank=True, to='broker.Address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ManyToManyField(blank=True, to='broker.Company'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.ManyToManyField(blank=True, to='broker.Email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.ManyToManyField(blank=True, to='broker.Phone'),
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.ManyToManyField(blank=True, to='broker.Address'),
        ),
    ]
