# Generated by Django 4.0.1 on 2022-06-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seeking',
            old_name='min_size_qm',
            new_name='min_size_sq_m',
        ),
    ]
