# Generated by Django 4.0.1 on 2022-06-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_rename_min_size_qm_seeking_min_size_sq_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeking',
            name='must_have_internet',
            field=models.BooleanField(default=False),
        ),
    ]
