# Generated by Django 4.0.1 on 2022-09-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_seeking_must_have_internet'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='note_de',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='matching',
            name='note_en',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='matching',
            name='note_es',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='matching',
            name='note_fr',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='matching',
            name='note_it',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='matching',
            name='status_de',
            field=models.CharField(choices=[('possible', 'POSSIBLE'), ('pending', 'PENDING'), ('closed', 'CLOSED')], default='possible', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='matching',
            name='status_en',
            field=models.CharField(choices=[('possible', 'POSSIBLE'), ('pending', 'PENDING'), ('closed', 'CLOSED')], default='possible', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='matching',
            name='status_es',
            field=models.CharField(choices=[('possible', 'POSSIBLE'), ('pending', 'PENDING'), ('closed', 'CLOSED')], default='possible', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='matching',
            name='status_fr',
            field=models.CharField(choices=[('possible', 'POSSIBLE'), ('pending', 'PENDING'), ('closed', 'CLOSED')], default='possible', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='matching',
            name='status_it',
            field=models.CharField(choices=[('possible', 'POSSIBLE'), ('pending', 'PENDING'), ('closed', 'CLOSED')], default='possible', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='seeking',
            name='notes_de',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='seeking',
            name='notes_en',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='seeking',
            name='notes_es',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='seeking',
            name='notes_fr',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='seeking',
            name='notes_it',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='seeking',
            name='occupation_de',
            field=models.CharField(blank=True, help_text='Type of job that this tenant/buyer has', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='seeking',
            name='occupation_en',
            field=models.CharField(blank=True, help_text='Type of job that this tenant/buyer has', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='seeking',
            name='occupation_es',
            field=models.CharField(blank=True, help_text='Type of job that this tenant/buyer has', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='seeking',
            name='occupation_fr',
            field=models.CharField(blank=True, help_text='Type of job that this tenant/buyer has', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='seeking',
            name='occupation_it',
            field=models.CharField(blank=True, help_text='Type of job that this tenant/buyer has', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='seeking',
            name='seeking_type_de',
            field=models.CharField(choices=[('rental', 'RENTAL'), ('for_sale', 'FOR_SALE')], default='rental', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='seeking',
            name='seeking_type_en',
            field=models.CharField(choices=[('rental', 'RENTAL'), ('for_sale', 'FOR_SALE')], default='rental', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='seeking',
            name='seeking_type_es',
            field=models.CharField(choices=[('rental', 'RENTAL'), ('for_sale', 'FOR_SALE')], default='rental', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='seeking',
            name='seeking_type_fr',
            field=models.CharField(choices=[('rental', 'RENTAL'), ('for_sale', 'FOR_SALE')], default='rental', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='seeking',
            name='seeking_type_it',
            field=models.CharField(choices=[('rental', 'RENTAL'), ('for_sale', 'FOR_SALE')], default='rental', max_length=8, null=True),
        ),
    ]
