# Generated by Django 4.0.1 on 2022-05-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(blank=True, default='SmartEstate', max_length=32, null=True)),
                ('cover_text', models.TextField(blank=True, default='Welcome to SmartEstate! SmartEstate lets real estate owners, brokers, managers, landlords, etc. manage their listings all from one conventient, cloud native web app. Please stay tuned, more info is coming soon.', help_text='The text displayed on the front page of your site', max_length=4096, null=True)),
                ('theme', models.CharField(choices=[('base', 'BASE'), ('frankfurt', 'FRANKFURT'), ('wiesbaden', 'WIESBADEN'), ('munich', 'MUNICH')], default='base', max_length=16)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='uploads/config/')),
            ],
        ),
    ]
