# Generated by Django 4.0.1 on 2022-06-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='show_filter_search_in_listview',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='config',
            name='show_filter_search_on_homepage',
            field=models.BooleanField(default=True),
        ),
    ]
